aiAgent:
  image:
    repository: raulcabm/agent
    tag: testt12
    pullPolicy: IfNotPresent
mcp:
  image:
    repository: raulcabm/mcp
    tag: testt10
    pullPolicy: IfNotPresent

imagePullSecrets: [] # Default to an empty list