aiAgent:
  image:
    repository: ghcr.io/rancher-sandbox/rancher-ai-agent
    tag: v0.0.1-alpha.10
    pullPolicy: IfNotPresent
mcp:
  image:
    repository: ghcr.io/rancher-sandbox/rancher-ai-mcp
    tag: v0.0.1-alpha.11
    pullPolicy: IfNotPresent

imagePullSecrets: [] # Default to an empty list

llmModel:
ollamaUrl:
googleApiKey:
openaiApiKey:
langfuseSecretKey:
langfusePublicKey:
langfuseHost: