apiVersion: v1
kind: Service
metadata:
  name: rancher-ai-agent
  namespace: cattle-ai-system
spec:
  selector:
    app: rancher-ai-agent
  ports:
    - port: 80
      name: http
      targetPort: 8000
      protocol: TCP
  type: ClusterIP