apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rancher-ai-agent
  name: rancher-ai-agent
  namespace: cattle-ai-agent-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher-ai-agent
  template:
    metadata:
      labels:
        app: rancher-ai-agent
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.aiAgent.image.repository }}:{{ .Values.aiAgent.image.tag }}"
        imagePullPolicy: "{{ .Values.aiAgent.image.pullPolicy }}"
        name: agent
        env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: llm-config
                key: OPENAI_API_KEY
          - name: MODEL
            valueFrom:
              secretKeyRef:
                name: llm-config
                key: MODEL
          - name: OLLAMA_URL
            valueFrom:
              secretKeyRef:
                name: llm-config
                key: OLLAMA_URL
          - name: GOOGLE_API_KEY
            valueFrom:
              secretKeyRef:
                name: llm-config
                key: GOOGLE_API_KEY
          - name: SYSTEM_PROMPT
            valueFrom:
              secretKeyRef:
                name: llm-config
                key: SYSTEM_PROMPT
          - name: LANGFUSE_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: llm-config
                key: LANGFUSE_PUBLIC_KEY
          - name: LANGFUSE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: llm-config
                key: LANGFUSE_SECRET_KEY
          - name: LANGFUSE_HOST
            valueFrom:
              secretKeyRef:
                name: llm-config
                key: LANGFUSE_HOST
        ports:
         - containerPort: 8000
