apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher-ai-agent
  namespace: cattle-ai-system
  annotations:
  {{- if .Values.ingress.configurationSnippet }}
  nginx.ingress.kubernetes.io/configuration-snippet: |
    {{- template "configurationSnippet" . }}
  {{- end }}
  {{- if eq .Values.tls "external" }}
  nginx.ingress.kubernetes.io/ssl-redirect: "false"
  {{- else }}
    {{- if ne .Values.ingress.tls.source "secret" }}
      {{- $certmanagerVer :=  split "." .Values.certmanager.version -}}
      {{- if or (.Capabilities.APIVersions.Has "certmanager.k8s.io/v1alpha1") (and (gt (len $certmanagerVer._0) 0) (eq (int $certmanagerVer._0) 0) (lt (int $certmanagerVer._1) 11)) }}
  certmanager.k8s.io/issuer: rancher
      {{- else }}
  cert-manager.io/issuer: rancher
  cert-manager.io/issuer-kind: Issuer
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.ingress.includeDefaultExtraAnnotations }}
  nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
  nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
  nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  {{- end }}
spec:
{{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end }}
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - backend:
          service:
            name: rancher-ai-agent
            port:
              number: 80
        path: /agent
        pathType: {{ .Values.ingress.pathType }}
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: {{ .Values.ingress.tls.secretName }}