apiVersion: v1
kind: Secret
metadata:
  name: llm-config
  namespace: cattle-ai-agent-system
type: Opaque
stringData:
  OPENAI_API_KEY: "{{ .Values.openaiApiKey }}"
  SYSTEM_PROMPT: "{{ .Values.systemPrompt }}"
  MODEL: "{{ .Values.llmModel }}"
  OLLAMA_URL: "{{ .Values.ollamaUrl }}"
  GOOGLE_API_KEY: "{{ .Values.googleApiKey }}"
  LANGFUSE_HOST: "{{ .Values.langfuseHost }}"
  LANGFUSE_PUBLIC_KEY: "{{ .Values.langfusePublicKey }}"
  LANGFUSE_SECRET_KEY: "{{ .Values.langfuseSecretKey }}"