apiVersion: v1
kind: Secret
metadata:
  name: llm-config
  namespace: cattle-ai-agent-system
type: Opaque
stringData:
  OPENAI_API_KEY: "{{ .Values.openaiApiKey }}"
  SYSTEM_PROMPT: "{{ .Values.systemPrompt }}"
  MODEL: "{{ .Values.model }}"
  OLLAMA_URL: "{{ .Values.ollamaUrl }}"
  GOOGLE_API_KEY: "{{ .Values.googleApiKey }}"