apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rancher-mcp-server
  name: rancher-mcp-server
  namespace: cattle-ai-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher-mcp-server
  template:
    metadata:
      labels:
        app: rancher-mcp-server
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.mcp.image.repository }}:{{ .Values.mcp.image.tag }}"
        imagePullPolicy: "{{ .Values.mcp.image.pullPolicy }}"
        name: agent
        ports:
         - containerPort: 8000
