name: Publish Helm Chart

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from Git tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Update Chart.yaml with new version
        # Use sed to replace the version and appVersion.
        run: |
          echo "Updating chart to version ${{ env.VERSION }}"
          sed -i "s/^version: .*/version: ${{ env.VERSION }}/" ./chart/Chart.yaml
          sed -i "s/^appVersion: .*/appVersion: \"${{ env.VERSION }}\"/" ./chart/Chart.yaml
          
          echo "--- Chart.yaml after update ---"
          cat ./chart/Chart.yaml
          echo "------------------------------"

      - name: Commit version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add chart/Chart.yaml
          git commit -m "Bump chart to version ${{ env.VERSION }}" || echo "No changes to commit"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"